In [2]:
import torch
print(torch.__version__)

2.0.1+cpu


# Introduction to Tensors

In [4]:
# scalars
scalar  = torch.tensor(7)
print(scalar)

# get tensor back as regular integer
print(scalar.item())

tensor(7)
7


In [11]:
# vectors 
vector_a  = torch.tensor([7,7])
# print vector_a
print(f'vector_a: {vector_a}')
# getting the dimensions
print(f'Dimensions of vector_a: {vector_a.ndim}')

# shape of the vector
print(f'Shape of vector_a: {vector_a.shape}')

vector_a: tensor([7, 7])
Dimensions of vector_a: 1
Shape of vector_a: torch.Size([2])


In [22]:
# MATRIX
MATRIX_a = torch.tensor([[7,8],
                        [9,10] ])
print(f'matrix_a: {MATRIX_a}')
# getting the dimensions
print(f'Dimensions of matrix_a: {MATRIX_a.ndim}')

# shape of the vector
print(f'Shape of matrix_a: {MATRIX_a.shape}')

matrix_a: tensor([[ 7,  8],
        [ 9, 10]])
Dimensions of matrix_a: 2
Shape of matrix_a: torch.Size([2, 2])


In [24]:
# TENSORS
TENSOR_a = torch.tensor([[[1,2,3],
                          [4,6,9],
                          [10,56,23]]])
print(f'Tensor_a: {TENSOR_a} \n')
# getting the dimensions
print(f'Dimensions of TENSOR_a: {TENSOR_a.ndim} \n')

# shape of the vector
print(f'Shape of TENSOR_a: {TENSOR_a.shape}\n')

# shape of 1, 3 ,3 means we have a one 3 by 3 tensor
print(f'Element in Dimension 0: {TENSOR_a[0]}\n')

Tensor_a: tensor([[[ 1,  2,  3],
         [ 4,  6,  9],
         [10, 56, 23]]]) 

Dimensions of TENSOR_a: 3 

Shape of TENSOR_a: torch.Size([1, 3, 3])

Element in Dimension 0: tensor([[ 1,  2,  3],
        [ 4,  6,  9],
        [10, 56, 23]])



### Random Tensors  


In [34]:
## Create random tensor of size 3,4

random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.8852, 0.2737, 0.2925, 0.0913],
        [0.4599, 0.8431, 0.7110, 0.1341],
        [0.1035, 0.2331, 0.3940, 0.5951]])


### Zeros and Ones

By default tensors are of float32 dtype

In [37]:
### Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
### Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [39]:
# using torch.arange
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
### Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes 

In [48]:
float_32_tensor = torch.tensor([4.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

# print the data type
float_32_tensor.dtype

torch.float32

In [44]:
x = torch.tensor([5,7,8],dtype=torch.float16)
y = x.type(torch.uint8)

x * y

tensor([25., 49., 64.], dtype=torch.float16)

### Tensor Attributes

1. Tensor not right datatype - to do get datattype from tensor, use `tensor.dtype`  
2. Tensor not right shape - use `tensor.shape` to get shape of tensor
3. Tensor not on right device - to get device from tensor use `tensor.device`

In [49]:
# Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3256, 0.7304, 0.2620, 0.3581],
        [0.1345, 0.5460, 0.9285, 0.4208],
        [0.0707, 0.3310, 0.1346, 0.1280]])

In [52]:
### Tensor Details
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Tensor shape: {some_tensor.shape}")
print(f"Tensor Device: {some_tensor.device}")

tensor([[0.3256, 0.7304, 0.2620, 0.3581],
        [0.1345, 0.5460, 0.9285, 0.4208],
        [0.0707, 0.3310, 0.1346, 0.1280]])

Datatype of tensor: torch.float32
Tensor shape: torch.Size([3, 4])
Tensor Device: cpu


### Manipulating Tensors ( Tensor Operations)

Tensor Operations Include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [57]:
### Create a tensor and add 10
tensor = torch.tensor([3,4,6])
tensor + 10


tensor([13, 14, 16])

In [58]:
### Multiply tensor by 10
tensor * 10


tensor([30, 40, 60])

In [59]:
# subtract 10
tensor - 10

tensor([-7, -6, -4])

In [60]:
### Using Pytorch In-built functions

# multiplication
torch.mul(tensor,10)

tensor([30, 40, 60])

In [61]:
### addition
torch.add(tensor,10)

tensor([13, 14, 16])