In [2]:
import torch
import numpy as np
print(torch.__version__)

2.0.1+cpu


# Introduction to Tensors

In [3]:
# scalars
scalar  = torch.tensor(7)
print(scalar)

# get tensor back as regular integer
print(scalar.item())

tensor(7)
7


In [4]:
# vectors 
vector_a  = torch.tensor([7,7])
# print vector_a
print(f'vector_a: {vector_a}')
# getting the dimensions
print(f'Dimensions of vector_a: {vector_a.ndim}')

# shape of the vector
print(f'Shape of vector_a: {vector_a.shape}')

vector_a: tensor([7, 7])
Dimensions of vector_a: 1
Shape of vector_a: torch.Size([2])


In [5]:
# MATRIX
MATRIX_a = torch.tensor([[7,8],
                        [9,10] ])
print(f'matrix_a: {MATRIX_a}')
# getting the dimensions
print(f'Dimensions of matrix_a: {MATRIX_a.ndim}')

# shape of the vector
print(f'Shape of matrix_a: {MATRIX_a.shape}')

matrix_a: tensor([[ 7,  8],
        [ 9, 10]])
Dimensions of matrix_a: 2
Shape of matrix_a: torch.Size([2, 2])


In [6]:
# TENSORS
TENSOR_a = torch.tensor([[[1,2,3],
                          [4,6,9],
                          [10,56,23]]])
print(f'Tensor_a: {TENSOR_a} \n')
# getting the dimensions
print(f'Dimensions of TENSOR_a: {TENSOR_a.ndim} \n')

# shape of the vector
print(f'Shape of TENSOR_a: {TENSOR_a.shape}\n')

# shape of 1, 3 ,3 means we have a one 3 by 3 tensor
print(f'Element in Dimension 0: {TENSOR_a[0]}\n')

Tensor_a: tensor([[[ 1,  2,  3],
         [ 4,  6,  9],
         [10, 56, 23]]]) 

Dimensions of TENSOR_a: 3 

Shape of TENSOR_a: torch.Size([1, 3, 3])

Element in Dimension 0: tensor([[ 1,  2,  3],
        [ 4,  6,  9],
        [10, 56, 23]])



### Random Tensors  


In [7]:
## Create random tensor of size 3,4

random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.0719, 0.6968, 0.8222, 0.7105],
        [0.4195, 0.8419, 0.3137, 0.0759],
        [0.3210, 0.2570, 0.5353, 0.6443]])


### Zeros and Ones

By default tensors are of float32 dtype

In [8]:
### Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
### Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [10]:
# using torch.arange
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
### Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes 

In [12]:
float_32_tensor = torch.tensor([4.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

# print the data type
float_32_tensor.dtype

torch.float32

In [13]:
x = torch.tensor([5,7,8],dtype=torch.float16)
y = x.type(torch.uint8)

x * y

tensor([25., 49., 64.], dtype=torch.float16)

### Tensor Attributes

1. Tensor not right datatype - to do get datattype from tensor, use `tensor.dtype`  
2. Tensor not right shape - use `tensor.shape` to get shape of tensor
3. Tensor not on right device - to get device from tensor use `tensor.device`

In [14]:
# Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4629, 0.5143, 0.6206, 0.6550],
        [0.3426, 0.2913, 0.3756, 0.8472],
        [0.8727, 0.7351, 0.5630, 0.5246]])

In [15]:
### Tensor Details
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Tensor shape: {some_tensor.shape}")
print(f"Tensor Device: {some_tensor.device}")

tensor([[0.4629, 0.5143, 0.6206, 0.6550],
        [0.3426, 0.2913, 0.3756, 0.8472],
        [0.8727, 0.7351, 0.5630, 0.5246]])

Datatype of tensor: torch.float32
Tensor shape: torch.Size([3, 4])
Tensor Device: cpu


### Manipulating Tensors ( Tensor Operations)

Tensor Operations Include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [16]:
### Create a tensor and add 10
tensor = torch.tensor([3,4,6])
tensor + 10


tensor([13, 14, 16])

In [17]:
### Multiply tensor by 10
tensor * 10


tensor([30, 40, 60])

In [18]:
# subtract 10
tensor - 10

tensor([-7, -6, -4])

In [19]:
### Using Pytorch In-built functions

# multiplication
torch.mul(tensor,10)

tensor([30, 40, 60])

In [20]:
### addition
torch.add(tensor,10)

tensor([13, 14, 16])

### Matrix Multiplication

Two ways of doing multiplication in Neural Networks or Deep Learning

* Element-wise multiplication
* Matrix multiplication ( dot product)

2 Rules for matrix multiplication
1. Inner Dimensions must match  
`(3,2) @ (3,2)` won't work  
`(3,2) @ (2,3)` will work  
2. The resulting matrix has shape of the outter dimensions  
`(2,3) @ (3,2)` -> `(2,2)`  
`(3,2) @ (2,3)` -> `(3,3)`

In [21]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)

torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(2,3)

result_tensor = torch.matmul(tensor_a,tensor_b)
print(f"Dot product of {tensor_a.shape} and {tensor_b.shape}")
print(f"Results in {result_tensor.shape}")
print(result_tensor)

Dot product of torch.Size([3, 2]) and torch.Size([2, 3])
Results in torch.Size([3, 3])
tensor([[0.4277, 0.3763, 0.2970],
        [0.0864, 0.0488, 0.0594],
        [0.5396, 0.6863, 0.3788]])


In [ ]:
# Element-wise multiplication
print(f"{tensor} * {tensor}")
print(f"Equals: {tensor * tensor}")

tensor([3, 4, 6]) * tensor([3, 4, 6])
Equals: tensor([ 9, 16, 36])


In [ ]:
# Matrix Mulitpliaction
torch.matmul(tensor,tensor)

tensor(61)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(61)
CPU times: total: 0 ns
Wall time: 11.6 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 997 µs


tensor(61)

Using Pytorch in-built functions is much faster

### One of the most common error in Deep Learning `shape errors`

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Fix tensor shape using Transpose operation  

A **transpose** switches the axes of tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Dot product works because we have transposed tensor_B
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiply: {tensor_A.shape} @ {tensor_B.T.shape} <- Inner Dimensions match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiply: torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner Dimensions match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


### Tensor Aggreagtion ( Min, Max, Mean, Sum etc)

In [ ]:
## Create tensor
x = torch.arange(2,100,10)
x, x.dtype

(tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92]), torch.int64)

In [ ]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Max value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
## NOTE: torch.mean() requires float tensor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [22]:
# Sum
torch.sum(x), x.sum()

(tensor(20., dtype=torch.float16), tensor(20., dtype=torch.float16))

### Finding Positional Max and Min

In [ ]:
x

tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [23]:
# find index position with min value in the tensor
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(2)

In [ ]:
# find index position with max value in the tensor
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(92)

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to defined shape
* View - Return a view of the input tensor of certain certain shape but keep in memory
* Stacking - COmbine multiple tensors on top of each (vstack) or side by side (hstack)
* Squeezing -  Squeezing removes dimensions of size 1 from a tensor.
* Unsqueezing -  Unsqueezing is the opposite of squeezing. It adds dimensions of size 1 to a tensor. 
* Permute - Return a view of the inout with dimensions permutted (swapped)

In [ ]:
# Creating tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Adding an extra dimension
x_reshaped  = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Changing the View
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (view of tensor shares the same memory as the original tensor input)
z[:,0] = 6
z, x

(tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from tensor
# Cretae tensor
x_new = torch.rand(1,2,5)
print(f"Original tensor shape: {x_new.shape}")
print(f"Original tensor: {x_new}")

# Remove extra dimensions
x_squeeze = x_new.squeeze()
print(f"\nSqueezed tensor shape: {x_squeeze.shape}")
print(f"Squeezed tensor: {x_squeeze}")


Original tensor shape: torch.Size([1, 2, 5])
Original tensor: tensor([[[0.3112, 0.8370, 0.4149, 0.6235, 0.4951],
         [0.0692, 0.7562, 0.6951, 0.4662, 0.3162]]])

Squeezed tensor shape: torch.Size([2, 5])
Squeezed tensor: tensor([[0.3112, 0.8370, 0.4149, 0.6235, 0.4951],
        [0.0692, 0.7562, 0.6951, 0.4662, 0.3162]])


In [ ]:
# torch unsqueeze() - adds single dimension to target tensor at speicified dim
print(f"Previous shape: {x_squeeze.shape}")
print(f"Previous target: {x_squeeze}")


# add extra dimension
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print(f"\n New tensor shape: {x_unsqueeze.shape}")
print(f'New tensor: {x_unsqueeze}')


Previous shape: torch.Size([2, 5])
Previous target: tensor([[0.3112, 0.8370, 0.4149, 0.6235, 0.4951],
        [0.0692, 0.7562, 0.6951, 0.4662, 0.3162]])

 New tensor shape: torch.Size([1, 2, 5])
New tensor: tensor([[[0.3112, 0.8370, 0.4149, 0.6235, 0.4951],
         [0.0692, 0.7562, 0.6951, 0.4662, 0.3162]]])


In [ ]:
# torch.permute - rearranges the dimensions of target tensor in specified order

x_original = torch.rand(size=(224,224,3)) # (height, width, color channels)

# Permute original tensor to rearrange axis or dims order
# change the original tensor to color channels, height, width
x_permuted = torch.permute(x_original,(2,0,1))

print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


### Indexing Pytorch

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on the middle dim
# x[0][0]
x[0,0]

tensor([1, 2, 3])

In [ ]:
# index on the most inner bracket
x[0,0,0]

tensor(1)

In [ ]:
# get all values of of 0th and 1st dimensio but only index 1st and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd didmension
x[:,1,1]


tensor([5])

In [ ]:
# get index 0th and 1st dimension and all values of the 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# Index x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch and Numpy 

In [ ]:
# NumPy array to tensor
array = np.arange(1.0,8)
tensor = torch.from_numpy(array)
# warning: when converting from numpy to pytorch, pytorch maintains numpy's default dtype (float64)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change value of array, what happens to the tensor?
# changing array values does not affect tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change tensor, what happems to the numpy_tensor?
#numpy_tensor is not affected
tensor = tensor + 2
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [24]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Check GPU Access with Pytorch

In [25]:
torch.cuda.is_available()

False

In [27]:
# setting the device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'