In [9]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

### 2. Create a random tensor with shape (7, 7).

In [7]:
random_seed = 0
torch.manual_seed(random_seed)

# Create random tensor
tensor = torch.rand(size=(7,7))
tensor


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [8]:
torch.manual_seed(random_seed)

# Create another random tensor
tensor_B = torch.rand(size=(1,7))

# Perform matrix multiplication 
result = torch.matmul(tensor, tensor_B.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 4. Set the random seed to 0 and do 2 & 3 over again.

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:
random_seed = 1234
torch.cuda.manual_seed(random_seed)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [11]:
random_seed = 1234
# create random tensor
torch.manual_seed(random_seed)
tensor_1 = torch.rand(size=(2,3)).to(device)

# create another tensor
torch.manual_seed(random_seed)
tensor_2 = torch.rand(size=(2,3)).to(device)
print(f'Device: {device}')
tensor_1, tensor_2


Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
# dot product
result = torch.matmul(tensor_1, tensor_2.T)
result, result.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Maximum value
print(f'Maximum value: {torch.max(result)}')

# Minimum Value
print(f"Minimum Value: {torch.min(result)}")

Maximum value: 0.628727912902832
Minimum Value: 0.21611443161964417


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
#Maximum Index Value (argmax)
print(f'Maximum Index Value: {torch.argmax(result)}')


#Minimum Index Value (argmin)
print(f"Minimum Index Value: {torch.argmin(result)}")

Maximum Index Value: 3
Minimum Index Value: 1


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
random_seed = 7
torch.manual_seed(random_seed)
# create random tensor
tensor_c = torch.rand(size=(1,1,1,10))

# remove all 1 dimensions
new_tensor = torch.squeeze(tensor_c)

print(f"Original Tensor: {tensor_c}")
print(f"Original Tensor shape: {tensor_c.shape}")

print(f"\nNew tensor: {new_tensor}")
print(f"New tensor shape: {new_tensor.shape}")

Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original Tensor shape: torch.Size([1, 1, 1, 10])

New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New tensor shape: torch.Size([10])
